services:
  db:
    container_name: recycle_chain_workshop_db
    image: postgres
    restart: always
    ports:
      - 2023:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data_recycle_chain_workshop:/var/lib/postgresql/data

  app:
    image: node:latest
    container_name: recycle_app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "./entrypoint.sh"
    env_file:
      - .env
    ports:
      - "3001:3000" # API
      - "3002:3002" # Web
      - "3003:3003" # UI
      - "5555:5555" # Prisma
      - "8081:8081" # Prisma
    depends_on:
      - db

volumes:
  db_data_recycle_chain_workshop:

