services:
  db:
    container_name: recycle_chain_workshop_db
    image: postgres
    restart: always
    ports:
      - 2023:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data_recycle_chain_workshop:/var/lib/postgresql/data

  app:
    image: node:latest
    working_dir: /app/apps/api
    volumes:
      - ../..:/app
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    ports:
      - "3001:3000"
      - "3002:3002"
      - "3004:3003"
      - "5555:5555"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  db_data_recycle_chain_workshop:
